title: Your awesome title
author: GitHub User
email: your-email@domain.com
description:This blog help you to build your self
twitter_username: Bondith
github_username:  Bondith

show_excerpts: false

theme: jekyll-theme-minimal
